name: Build CV

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # CV, Cover letter, CV with Cover letter
        cv_type: [CV, CL, CVCL]
    
    steps:
    - uses: actions/checkout@v4

    - name: Switch build type
      run: |
        if [ "${{ matrix.cv_type }}" == "CV" ]; then
          sed -i '/^\\include{cover_letter}/s/^/%/' index.tex
          sed -i '/^%\\include{cv}/s/^%//' index.tex
        elif [ "${{ matrix.cv_type }}" == "CVCL" ]; then
          sed -i '/^\\include{cover_letter}/s/^%//' index.tex
          sed -i '/^%\\include{cv}/s/^%//' index.tex
        else
          sed -i '/^\\include{cover_letter}/s/^%//' index.tex
          sed -i '/^%\\include{cv}/s/^/%/' index.tex
        fi

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: index.tex

    - name: Upload Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: R-Krishnan-${{matrix.cv_type}}-${{ github.run_id }}-${{ github.run_number }}.pdf
        path: index.pdf
